.github/dependabot.yml
.github/workflows/check.yml
.github/workflows/docker.yml

In order to improve our security posture with GitHub Actions usage. I've made a version pinning ether to commit hash or to specific version.
Additionally added `dependabot` to track GHA version changes.
Related issues and policy:
https://github.com/paritytech/ci_cd/issues/114
https://github.com/paritytech/ci_cd/issues/464
https://github.com/paritytech/ci_cd/wiki/Policies-and-regulations:-GitHub-Actions-usage-policies

Pin GHA versions and add dependabot

---

xcm-playground.toml

On https://github.com/paritytech/trappist/pull/63 I reduced the number of relay validators to save up resources.
That caused parachain 3000 to not be able to produce blocks anymore. It turns out that we need at least three relay validators so that all three parachains can produce blocks.
This PR fixes this by adding a new relay validator (`charlie`).
It also fixes the `addToGenesis` fields to camel case form `add_to_genesis`.

fix zombienet toml

---

.github/workflows/check.yml
Cargo.lock
node/Cargo.toml
node/src/command.rs
node/src/service.rs
pallets/asset-registry/Cargo.toml
pallets/asset-registry/README.md
pallets/asset-registry/src/lib.rs
pallets/asset-registry/src/mock.rs
pallets/asset-registry/src/tests.rs
pallets/asset-registry/src/weights.rs
primitives/xcm/Cargo.toml
runtime/Cargo.toml
runtime/src/constants.rs
runtime/src/contracts.rs
runtime/src/lib.rs
runtime/src/xcm_config.rs

- updated dex pallet to 0.9.30
- updated [pallet-contracts-xcm to 0.9.30](https://github.com/paritytech/pallet-contracts-xcm/tree/trappist/polkadot-v0.9.30)
- updated trappist config to 0.9.30
- updated CI workflow to install protoc, required by prost-build
Note: the dex pallet PR is awaiting merge, so currently the trappist config in this PR points to my fork. This can be updated once merged and the substrate-dex repository has been moved under paritytech.

build(deps): update dependencies to polkadot v0.9.30

---

integration-tests/asset-registry/0_reserve_transfer.yml

The reserve-transfer integration test is failing after updating to 0.9.30 with the following error:
`Expected Attribute: 'XcmV2TraitsOutcome' : "1,000,000,000" | Received Attribute: 'XcmV2TraitsOutcome' : "654,608,000" `
https://github.com/paritytech/cumulus/commit/27d05a38e151794c30880592d5bcc3b2aa58a95d#diff-ba1aa16da44c3c45953fbb3ae34a4a3ed4d6d898f1bfe16b32d0fd91daf0f80b shows a downward adjustment of the expected weight in the statemine integration test, along with threshold, so this PR simply applys the same fix.

test: update expected polkadotXcm.attempted event value (with threshold)

---

README.md

xcm-playground.toml refers to "./bin/polkadot-parachain" rather than `polkadot-collator`, and cumulus build results in `polkadot-parachain` binary.

docs: correct binary name

---

.github/workflows/check.yml

- use [actions-rs](https://github.com/actions-rs/toolchain) to simplify Rust toolchain installation, inline with other Parity repositories
- allow local workflow runs via [act](https://github.com/nektos/act) to easily validate before pushing

Minor CI improvements

---

integration-tests/asset-registry/0_reserve_transfer.yml
primitives/xcm/src/lib.rs
runtime/src/xcm_config.rs

close #51 
`ConvertedRegisteredAssetId` is a custom implementation of the `MatchesFungibles` trait that allows `ReservedFungiblesTransactor` to coexist with `LocalFungiblesTransactor` without having its execution priority block the second Transactor from ever being triggered.
Whenever `ConvertedRegisteredAssetId` can't find the Asset in `AssetRegistry` (`what = ConvertAssetId::convert_ref(id)`), a `MatchError::AssetNotFound` is thrown (instead of `MatchError::AssetIdConversionFailed`).
That allows the [`TransactAsset` trait implementation for Tuple](https://github.com/paritytech/polkadot/blob/3711c6f9b2a30ab6cc888917ad0bbfa64266d41b/xcm/xcm-executor/src/traits/transact_asset.rs#L117) to simply bypass the `ReservedFungiblesTransactor` without halting the XCM execution with a …

Custom Matcher (ConvertedRegisteredAssetId) for ReservedFungiblesTransactor

---

.github/workflows/check.yml

Adds variable to define version of `nightly`, which is then used for toolchain installation and to check formatting.
Tested successfully locally using `act`, so _should_ work fine in GH Actions.

CI: Cache build artifacts

---

.github/workflows/check.yml
node/Cargo.toml

Build failing when running `cargo build --release` is counter-intuitive.
Build the trappist-runtime by default (node's default feature).

Build trappist runtime by default

---

README.md

Simply adds CI status badges to the readme.
The other correction is due to the fact that cargo test mixes up the test trace output (as run in parallel) so it was removed from the command.

docs: add ci status badges to readme

---

.github/workflows/simulate.yml

Caching action doesn't seem to take `working-directory` set a job level into account so manually added it to the caching step.
Also improved name of test results output.

ci: fix simulate workflow artifact caching

---

xcm-simulator/src/lib.rs
xcm-simulator/src/parachains/base.rs
xcm-simulator/src/parachains/trappist.rs

Re-using `LocalAssetTransactor` from main runtimes was causing incorrect `Balances` type usage, resulting in stored events which could not be decoded back to mock runtime events:
`ERROR runtime::storage: Corrupted state at ..`

fix: add local asset transactor type definition

---

xcm-simulator/src/lib.rs
xcm-simulator/src/parachains/base.rs
xcm-simulator/src/parachains/trappist.rs

Additional type aliases defined within mock base runtime to correctly resolve types, rather than re-using from actual runtimes.
Also added small helper function for optionally outputting events, useful when debugging.

fix(base): add local asset transactor type definition

---

integration-tests/asset-registry/0_reserve_transfer.yml

The latest release version of the `parachains-integration-tests` tool (v2.1) added yaml test file format validation (enforcement).

fix: integration test formatting

---

xcm-simulator/src/tests/xcm_asset_trap.rs

Minor suggestion for test variables, simply moving them closer to where they are used so easier to read. Also removes unnecessary path prefixes.

refactor: move variables closer to usage

---

Cargo.lock
node/Cargo.toml
node/cli/Cargo.toml
node/cli/src/cli.rs
node/cli/src/command.rs
node/service/Cargo.toml
node/service/src/lib.rs
pallets/asset-registry/Cargo.toml
pallets/asset-registry/README.md
primitives/xcm/Cargo.toml
rpc/Cargo.toml
rpc/src/lib.rs
runtime/base/Cargo.toml
runtime/base/src/contracts.rs
runtime/base/src/lib.rs
runtime/trappist/Cargo.toml
runtime/trappist/src/contracts.rs
runtime/trappist/src/lib.rs
xcm-simulator/Cargo.toml
xcm-simulator/src/tests/misc.rs
xcm-simulator/src/tests/xcm_asset_trap.rs
xcm-simulator/src/tests/xcm_use_cases.rs

Closes #97 
- updated [dex pallet to 0.9.32](https://github.com/paritytech/substrate-dex/pull/40) 
- updated [pallet-contracts-xcm to 0.9.32](https://github.com/paritytech/pallet-contracts-xcm/tree/trappist/polkadot-v0.9.32)
- updated dependencies to 0.9.32
- updated codebase according to polkadot-v0.9.32

Updated dependencies to 0.9.32

---

Cargo.lock
node/Cargo.toml
node/cli/Cargo.toml
node/cli/src/cli.rs
node/cli/src/command.rs
node/service/Cargo.toml
node/service/src/lib.rs
pallets/asset-registry/Cargo.toml
pallets/asset-registry/README.md
pallets/asset-registry/src/mock.rs
primitives/xcm/Cargo.toml
rpc/Cargo.toml
runtime/base/Cargo.toml
runtime/base/src/lib.rs
runtime/trappist/Cargo.toml
runtime/trappist/src/lib.rs
xcm-simulator/Cargo.toml
xcm-simulator/src/parachains/asset_reserve.rs
xcm-simulator/src/parachains/base.rs
xcm-simulator/src/parachains/trappist.rs

Closes #98 
- updated https://github.com/paritytech/substrate-dex/pull/41
- updated [pallet-contracts-xcm to 0.9.33](https://github.com/paritytech/pallet-contracts-xcm/tree/trappist/polkadot-v0.9.33)
- updated dependencies to 0.9.33
- updated codebase according to polkadot-v0.9.33

updated dependencies to v0.9.33

---

Cargo.lock
node/Cargo.toml
node/cli/Cargo.toml
node/cli/src/command.rs
node/service/Cargo.toml
node/service/src/lib.rs
pallets/asset-registry/Cargo.toml
pallets/asset-registry/README.md
pallets/asset-registry/src/lib.rs
pallets/asset-registry/src/mock.rs
primitives/xcm/Cargo.toml
rpc/Cargo.toml
runtime/base/Cargo.toml
runtime/base/src/constants.rs
runtime/base/src/contracts.rs
runtime/base/src/lib.rs
runtime/trappist/Cargo.toml
runtime/trappist/src/constants.rs
runtime/trappist/src/contracts.rs
runtime/trappist/src/lib.rs
xcm-simulator/Cargo.toml
xcm-simulator/src/parachains/asset_reserve.rs
xcm-simulator/src/parachains/base.rs
xcm-simulator/src/parachains/template.rs
xcm-simulator/src/parachains/trappist.rs
xcm-simulator/src/relay_chain.rs
xcm-simulator/src/tests/misc.rs
xcm-simulator/src/tests/mod.rs
xcm-simulator/src/tests/xcm_asset_trap.rs
xcm-simulator/src/tests/xcm_use_cases.rs

Closes #122 
- updated https://github.com/paritytech/substrate-dex/pull/45
- updated [pallet-contracts-xcm to 0.9.36](https://github.com/paritytech/pallet-contracts-xcm/tree/trappist/polkadot-v0.9.36)
- updated dependencies to 0.9.36
- updated codebase according to polkadot-v0.9.36

upgraded to polkadot-v0.9.36

---

runtime/trappist/src/constants.rs
runtime/trappist/src/contracts.rs
runtime/trappist/src/lib.rs
runtime/trappist/src/xcm_config.rs

closes #154 
- Reduce deposit to 100th of the relay chain's (from a 10th)
- Reduce collator session length & enable contracts pallet unstable interface (as per https://github.com/paritytech/cumulus/pull/1748)
- Re-order pallets to retain the IDs from Contracts-rococo runtime (might not be needed but if anything relies on them on the Contracts testnet, this will make it transparent to migrate ... and it doesn't change anything for Trappist as they chain wasn't live before)
- Remove Cumulus spambot (aka Cumulus ping)

Align Trappist runtime w/ Contracts Rococo testnet runtime v0.9.37

---

README.md
node/Cargo.toml
node/cli/src/cli.rs
node/cli/src/lib.rs
node/service/src/chain_spec/stout.rs
node/service/src/chain_spec/trappist.rs
node/service/src/lib.rs
runtime/trappist/Cargo.toml
runtime/trappist/src/impls.rs

- update readme
- fix formatting
- fix warnings

Code cleanup

---

Cargo.lock
node/service/Cargo.toml
rpc/Cargo.toml
runtime/stout/Cargo.toml
runtime/trappist/Cargo.toml

Quick fix for pre-upgraded version of Trappist to be deployed on Rococo to point to proper branch of pallet-dex

Updated pallet-dex branch

---

pallets/asset-registry/src/benchmarking.rs
pallets/asset-registry/src/lib.rs
pallets/asset-registry/src/mock.rs
pallets/asset-registry/src/tests.rs
runtime/trappist/src/lib.rs

- Fix benchmarks. Benchmarks fail because of this check `ensure!(T::Assets::asset_exists(asset_id), Error::<T>::AssetDoesNotExist)`. The asset being used has to exist in the pallet responsible for storing assets (pallet_assets in our case)
- Refactor tests. Increased atomicity.

`asset-registry` refactoring

---

.github/workflows/build_docker.yml
.github/workflows/publish-docker.yml
Cargo.lock
node/Cargo.toml
node/cli/Cargo.toml
node/service/Cargo.toml
node/service/src/lib.rs
pallets/asset-registry/Cargo.toml
pallets/asset-registry/README.md
pallets/asset-registry/src/lib.rs
pallets/asset-registry/src/weights.rs
primitives/xcm/Cargo.toml
primitives/xcm/src/lib.rs
rpc/Cargo.toml
rpc/src/lib.rs
runtime/stout/Cargo.toml
runtime/stout/src/constants.rs
runtime/stout/src/contracts.rs
runtime/stout/src/lib.rs
runtime/stout/src/xcm_config.rs
runtime/trappist/Cargo.toml
runtime/trappist/src/constants.rs
runtime/trappist/src/contracts.rs
runtime/trappist/src/impls.rs
runtime/trappist/src/lib.rs
runtime/trappist/src/xcm_config.rs
xcm-playground.toml
xcm-simulator/Cargo.toml

Upgrades from polkadot-v0.9.37 to polkadot-v0.9.40 introducing XCM V3 and Weights V2. The detailed description of changes can be found here.
[ Polkadot v0.9.38](https://github.com/paritytech/polkadot/releases/tag/v0.9.38)
[Polkadot v0.9.39](https://github.com/paritytech/polkadot/releases/tag/v0.9.39)
[Polkadot v0.9.40](https://github.com/paritytech/polkadot/releases/tag/v0.9.40)
The upgrade introduced a lot of changes so feel free to comment on anything that could be improved or revised before the merge.
**Replaced `AssetId`for `AssetIdForTrustBackedAssets` .**
Modified in version v0.9.38 AssetId changed name implying that the Id comes from a TrustBackedAsset which based on the fact that this are intended to be minted on statemine would make sense.
```rust
impl pallet_assets::Config for …
```

Upgrade to v0.9.40

---

runtime/trappist/src/impls.rs
xcm-playground.toml

Fixes a previous error in the Lockdown `DmpMessageHandler` that would cause the chain to execute an Unreachable WASM instruction preventing the chain from producing blocks.
This was caused after replacing `DmpQueue` for `LockdownMode`in `cumulus_pallet_parachain_system`
```rust
impl cumulus_pallet_parachain_system::Config for Runtime {
....
type DmpMessageHandler = LockdownMode;
....
}
```

Lockdown DmpMessageHandler fix

---

pallets/lockdown-mode/src/benchmarking.rs
pallets/lockdown-mode/src/lib.rs
pallets/lockdown-mode/src/mock.rs
pallets/lockdown-mode/src/tests.rs

Lockdown mode ACTIVATED or DEACTIVATED is now part of the `GenesisConfig` of this pallet.
By default, the pallet will start with lockdown mode activated.
Closes: https://github.com/paritytech/trappist/issues/172

Add lockdown mode activation to lockdown-mode pallet's `GenesisConfig`

---

.github/templates/setup-worker/action.yaml
.github/workflows/check.yml
Cargo.lock

Because of [cache isolation strategy](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache) the cache generated in `main` branch is available to the rest. Which might be a problem when dependencies get updated. In case of a substrate version update when cache is recovered a worker receives lots of outdated targets that consume space, but cannot be reused.
The solution is to lock the `cargo.lock` file and remove the fallback cache recovery key.

Fix CI for substrate version update

---

runtime/trappist/src/lib.rs

Need to specify `SelfReserve` in `get_multi_asset`, because of the Matcher type in `LocalAssetTransactor`
```rust
pub type LocalAssetTransactor = CurrencyAdapter<
// Use this currency:
Balances,
// Use this currency when it is a fungible asset matching the given location or name:
IsConcrete<SelfReserve>, // <--- matcher
// Convert an XCM MultiLocation into a local account id:
LocationToAccountId,
// Our chain's account ID type (we can't get away without mentioning it explicitly):
AccountId,
// We don't track any teleports of `Balances`.
(),
>;
```

Fix XCM benchmarks

---

node/service/src/chain_spec/stout.rs
rpc/src/lib.rs
runtime/stout/src/lib.rs

Closes #203.
This PR is simple a concise: Adds the DEX pallet to stout runtime in order to simplify the service file refactor.

Adding dex pallet to stout

---

Cargo.lock
Cargo.toml
runtime/trappist/Cargo.toml
runtime/trappist/src/impls.rs
runtime/trappist/src/lib.rs

Removes `pallet_chess` from the Trappist Runtime as discussed in #167

chess-pallet removal

---

pallets/asset-registry/src/lib.rs
pallets/asset-registry/src/tests.rs

Improves the validation for the Multilocation received in `register_reserve_asset` inside the Asset-Registry pallet as discussed in #212.

Validate `MultiLocation` for asset-registry 

---

runtime/trappist/src/constants.rs
runtime/trappist/src/weights/xcm/mod.rs
runtime/trappist/src/xcm_config.rs

This PR fixes the reserve transfer asset from Rockmine to Trappist.
It adds the following Trader tuple:
```rust
pub type Trader = (
FixedRateOfFungible<RUsdPerSecond, ()>,
FixedRateOfFungible<RocPerSecond, ()>,
UsingComponents<WeightToFee, SelfReserve, AccountId, Balances, ToAuthor<Runtime>>,
);
```
As you can see, also `Roc`s can be computed as a reference value of 1 ROC = 7 RUSD"
```rust
pub RUsdPerSecond: (xcm::v1::AssetId, u128) = (
MultiLocation::new(1, X3(Parachain(1000), PalletInstance(50), GeneralIndex(1984))).into(),
default_fee_per_second() * 10
);
/// Roc = 7 RUSD
pub RocPerSecond: (AssetId, u128) = (MultiLocation::parent().into(), default_fee_per_second() * 70);
```
Also there was an issue with the pallet-xcm-benchmarking that was setting the weight for …

Fix xcm reserve transfer from Rockmine <> Trappist.

---

runtime/trappist/src/lib.rs

Use `SelfReserve` instead of `RelayLocation` in asset for `pallet_xcm_benchmarks::generic::claim_asset`

Fix `pallet_xcm_benchmarks::generic::claim_asset` benchmark

---

runtime/trappist/src/constants.rs

fix missing imports for `WEIGHT_REF_TIME_PER_SECOND` and `CENTS`

Fix missing usings

---

.github/workflows/check.yml

- move polka version into a variable
- use semver number to make it come up in searches when updating polkadot version
- kudos to @evilrobot-01 and his [comment](https://github.com/paritytech/trappist/pull/241#discussion_r1245006339) in #241

Refactor cache versioning on CI

---

node/src/command.rs
node/src/service.rs

Unify `TrappistRuntimeExecutor` and `StoutRuntimeExecutor` into a generic `RuntimeExecutor`. This change is inspired by @evilrobot-01 [comment](https://github.com/paritytech/trappist/pull/241#discussion_r1245155994)

Unify TrappistRuntimeExecutor and StoutRuntimeExecutor

---

node/src/chain_spec/trappist.rs

There is no point on starting Trappist locally with the lockdown mode activated. Since it was added many users thinks the chain does not work when it's launched locally. 
For this reason, i have updated the local chain spec of Trappist to start the chain without the lockdown mode activated.

Remove lockdown mode from GenesisConfig for local

---

Cargo.lock
pallets/asset-registry/src/lib.rs
runtime/stout/Cargo.toml
runtime/stout/src/lib.rs
runtime/stout/src/xcm_config.rs
runtime/trappist/src/weights/xcm/pallet_xcm_benchmarks_fungible.rs
runtime/trappist/src/xcm_config.rs

Basic changes that need to be implemented for allowing teleporting from and to AH from Trappist. Remove filter, add AH as trusted teleporter and fix Currency adapter.

Changing XCM config for allow teleport from and to AH

---

.github/workflows/build-runtime.yaml

Adds compressed wasm runtime, generated using srtool, to a published release. Still allows a manual trigger, which simply attaches artifacts to the workflow run.
Based on https://github.com/paritytech/polkadot/blob/master/.github/workflows/release-30_publish-draft-release.yml and https://github.com/paritytech/polkadot/blob/master/scripts/ci/changelog/templates/runtime.md.tera.
Example [release](https://github.com/evilrobot-01/trappist/releases/tag/3) and [manual run](https://github.com/evilrobot-01/trappist/actions/runs/5904892021).
Closes #242

ci(runtime): add deterministic runtime wasm to release

---

.github/workflows/check.yml
runtime/trappist/src/lib.rs

`ReceiveTeleportedAsset` was having `MAX_BLOCK` weight due to benchmark `TrustedTeleported` not matching the one from the runtime.

Fix benchmark TrustedTeleporter

---

.github/workflows/try-runtime.yml
node/src/cli.rs
node/src/command.rs
runtime/trappist/src/lib.rs

feat: use try-runtime-cli instead of command

---

Cargo.lock
pallets/withdraw-teleport/Cargo.toml
pallets/withdraw-teleport/src/lib.rs
runtime/trappist/src/xcm_config.rs

Implementation of `do_withdraw_and_teleport` call from #266 that also withdraws a derivative asset on origin chain 
For the sake of simplicity on wording:
Origin chain: Trappist
Destiny chain: Asset Hub
Pros: 
Users cannot longer exploit Trappist’s SovereignAccount on Asset Hub as they would need to have the same amount of funds as derivative on their Trappist's account than they would want to use for buying execution on Asset Hub.
ROCs used for buying execution on Asset Hub are not longer trapped and they are refunded as ROC on Asset Hub, not as the derivatives on Trappist.
Cons: 
Users must have derivative of ROC on Trappist apart from the HOP that they want to teleport. This could be done through a simple `ReserveAssetTransfer`
TODO: 
Refund surplus as derivative on origin chain to …

Withdraw derivative on origin

---

pallets/uniques/src/lib.rs
pallets/uniques/src/migration.rs
pallets/uniques/src/migration/v01.rs
runtime/trappist/src/lib.rs
scripts/uniques-uploader/src/main.rs
zombienet/trappist_rococo.toml

If useful, sleeps once arbitrary item block limit reached and also queries the number of items from collection to start minting from that position onwards. Did encounter one issue where metadata and item count on collection became out of sync, so should ideally be wrapped in a batch call.
Completes multi-block migration implementation for uniques pallet fork

feat: complete multi-block migration implementation

---

.github/templates/setup-worker/action.yaml
.github/workflows/check.yml
Cargo.toml

A few attempts to limit the disk usage during CI tests:
- Sets the default resolver for the virtual workspace as per https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html, mostly to silence the build warnings:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
- disables debug info for the test profile (debatable on whether this should be done)
- removes nightly from the setup-worker template
- uses Swatinem/rust-cache for 'smart rust caching', along with disabling …

ci: limit disk usage

---

zombienet/stout_rococo.toml

The zombienet config for the stout runtime would cause the zombienet startup to fail. This is because it attempted to open HRMP channels with the non-existent Trappist chain (id 1836).
The solution is to remove the attempted HRMP channels as the `full_network` config is for stout + trappist.

fix: stout runtime zombienet config

---

runtime/stout/src/lib.rs
runtime/trappist/src/lib.rs

See the following for more details: https://github.com/paritytech/trappist/issues/297.
Update the `pallet-uniques` string limits to match Polkadot's Asset hub. 
https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/parachains/runtimes/assets/asset-hub-polkadot/src/lib.rs#L683
```
pub const StringLimit: u32 = 128;
pub const KeyLimit: u32 = 32;
pub const ValueLimit: u32 = 64;
```

feat: update `pallet-uniques` string limits. #297

---

docker/trappist-parachain.dockerfile

Last run to build the collator image for Trappist v1.1.0 [failed](https://github.com/paritytech/trappist/actions/runs/6985009825/job/19008681490#step:5:1086) because the Rust version used is too old (v1.68.2).

Bump rust version in dockerfile for collator image

---

node/src/chain_spec/trappist.rs
scripts/hrmp_helper.sh
zombienet/full_network.toml
zombienet/stout_rococo.toml
zombienet/trappist_rococo.toml
zombienet/trappist_stout.toml

Due to current [issue](https://github.com/paritytech/polkadot-sdk/pull/1616) on genesis pre open, we comment out HRMP channels from zombienet config and create a helper script to spin up hrmp channels after zombienet spawn.

HRMP Workaround and Zombienet chores

---

zombienet/stout_rococo.toml
zombienet/trappist_rococo.toml

Same issue as the one found [here](https://github.com/paritytech/asset-transfer-api/pull/356).
I get the error
```
Error: Input("Error opening spec file `statemine-local`: No such file or directory (os error 2)")
```
when I try to run `zombienet` with the `trappist_rococo`/ `stout_rococo` toml files.
I use : 
- `polkadot` and `polkadot-parachain` binaries built in version `polkadot 1.6.0`
- `zombienet-macos` version `1.3.90`
I renamed `statemine` to `asset-hub-rococo` in the toml files of zombienet and then it runs as expected.

fix: renamed statemine in zombienet toml files

---

runtime/trappist/Cargo.toml
runtime/trappist/src/lib.rs
runtime/trappist/src/xcm_config.rs

Add bridged currency adapter to allow HOP generated on Ethereum to bridge into Trappist

feat: add bridged adapter

---

runtime/stout/src/lib.rs
runtime/trappist/Cargo.toml
runtime/trappist/src/lib.rs

This release is for testing EVM bridged assets through Snowbridge

Prepare Trappist v1.3.1 release
